# Generated by Django 6.0.7 on 2026-07-09 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('whatsapp', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número de WhatsApp deve conter apenas números, sem letras ou espaços, e ter entre 7 e 15 dígitos.', regex='^\\d{7,15}$')], verbose_name='Número de WhatsApp')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro/Zona de Residência')),
                ('compromisso_sigilo', models.BooleanField(verbose_name='Compromisso com o sigilo absoluto')),
                ('nao_discriminacao', models.BooleanField(verbose_name='Compromisso de não-discriminação')),
                ('proibicao_comercial', models.BooleanField(verbose_name='Ciente da proibição de fins comerciais/políticos')),
                ('disponibilidade_contribuicao', models.BooleanField(verbose_name='Disponibilidade para a contribuição de 100 MZN')),
                ('metodo_preferencial', models.CharField(choices=[('mpesa', 'M-Pesa'), ('term_mola', 'e-Mola'), ('mkesh', 'mKesh'), ('transferencia', 'Transferência Bancária'), ('tesoureiro', 'Direto ao Tesoureiro')], default='mpesa', max_length=20, verbose_name='Método Preferencial de Pagamento')),
                ('motivacao', models.TextField(verbose_name='O que te motivou a entrar no grupo?')),
                ('membro_ativo', models.BooleanField(verbose_name='Estás disposto a ser um membro ativo do grupo?')),
                ('doar_conhecimento', models.BooleanField(verbose_name='Estás disposto a doar teu conhecimento para fazer crescer o grupo?')),
                ('habilidades', models.TextField(verbose_name='Quais habilidades você reconhece ter que podem ajudar o grupo a crescer?')),
                ('aceitou_regras', models.BooleanField(verbose_name='Aceitou o Regulamento?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
